name: kestra
services:
  server:
    image: kestra/kestra:latest
    container_name: kestra-server
    user: 'root'
    command: server standalone
    volumes:
      - '/tmp/kestra-wd:/tmp/kestra-wd'
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/srv/$USER/docker/kestra/kestra/latest/rootfs/data/kestra:/app/storage
    ports:
      - '172.17.0.1:59057:8080'
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra-db:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: true
              username: "admin@kestra.io"
              password: ${APP_ADMIN_PASS:-password}
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: https://kestra.${BASE_DOMAIN_NAME}/
    depends_on:
      db:
        condition: service_started
    networks:
      - kestra

  db:
    image: postgres:latest
    container_name: kestra-db
    volumes:
      - '/var/lib/srv/$USER/docker/kestra/kestra/latest/rootfs/data/db/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - kestra

networks:
  keatra:
    name: kestra
    external: false
